### ISSUE TITLE
Not working in windows

### ISSUE THREAD

**Issue by Apptrion** [MacKentoch/react-director-admin-template#1]
Unable to launch the app in windows. The error message is also not clear, about any missing modules or dependencies.
`npm run dev-win`

**Comment by MacKentoch** [comment]
Could you check your current version of NodeJS:
```bash
node -v
```
**It requires minimum 6.x.x.** 
*This template is not finished so I did not add all details in README like minimum NodeJS version.*

> If you still need a previous version of node so use nvm to switch to v6 in this project.

When you've installed v6, be sure to drop previous `node_modules` content:
```bash
rm -rf node_modules
```

Then reinstall with the right version of NodeJS:
```bash
npm install
```
or 
```bash
yarn install
```

**Comment by Apptrion** [comment]
Sorry, I forgot to add earlier, after going thru the earlier message upgraded the node.

node -v  => v6.9.5
npm -v => 3.10.10

C:\react-director-admin-template>npm start-win

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\usrername\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.10 C:\Program Files\nodejs\node_modules\npm

I am still getting the above error. Searching further to figure out the error.

**Comment by MacKentoch** [comment]
@Apptrion Ok that is nothing, you just forgot `run`:
```bash
npm run start-win
```

It should be ok now.
