### ISSUE TITLE
Not able to compile SCSS's as its not watching for it after change in file!! Please Help

### ISSUE THREAD

**Issue by Harshithharry** [MacKentoch/react-director-admin-template#14]

**Comment by MacKentoch** [comment]
Hi,

**Please ensure running node 8 MAX.**
Node > 8 won't work (because of SCSS preprocessor...).

If not, reinstall all node_modules `from node 8`:

```bash
rm -rf node_modules && yarn install
```

**Comment by MacKentoch** [comment]
NOTE: upgrading all repository (WIP).

🤔 I may drop `SASS` or any other Style preprocessor needed (*getting rid of node js version restriction and over-complicated toolchain*) for a `css-in-js` solution (maybe Styled-Component).
