### ISSUE TITLE
Minified React error #31;

### ISSUE THREAD

**Issue by aviansh26dec** [MacKentoch/react-director-admin-template#19]
I have created build files and trying to access on ie 11/10 but it's not working on it. I am getting error <b>Minified React error #31;</b> in console.

**Comment by MacKentoch** [comment]
Hi @aviansh26dec 

I don't have windows...

May I ask you your help to test some fixes for IE:

In [index.js - entry point of the application](https://github.com/MacKentoch/react-director-admin-template/blob/master/src/front/index.js#L4) add these 2 lines at the very top of the file 

```javascript
import 'babel-polyfill';
import 'regenerator-runtime';
```

So an overview of the result:

```javascript
// flow

// #region imports
import 'babel-polyfill';
import 'regenerator-runtime';
// then all code as it is currently:
import React from 'react';
import { render } from 'react-dom';
import { AppContainer } from 'react-hot-loader';
import smoothScrollPolyfill from 'smoothscroll-polyfill';
import 'animate.css';
import './style/director-style.css';
import './style/highlight/darkula.css';
import './style/index.style.scss';
import Root from './Root';
// #endregion

// ETC....
```

**Comment by aviansh26dec** [comment]
I have tried your suggestion, but facing same issue.
![image](https://user-images.githubusercontent.com/24863578/59340327-676bca80-8d23-11e9-9b27-a5242ea5acb4.png)

**Comment by MacKentoch** [comment]
I don't understand it should have fixed.

Can you share the link next to the error please?

**Comment by aviansh26dec** [comment]
SCRIPT5022: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by aviansh26dec** [comment]
But, when I am testing on development mode its working fine on ie 11/10

**Comment by MacKentoch** [comment]
Thank you @aviansh26dec! 
You are very helpful.

So I guess I have to fix a wrong rendering like 
```js
<someElement>
  {AN_OBJECT_WHERE_IT_SHOULD_BE_A_CHILD}
</someElement>
```

**Comment by aviansh26dec** [comment]
Thank you @MacKentoch for the reply,

But, I do not understand. Please show me an example so I will fix it my end.

**Comment by MacKentoch** [comment]
I just have to find where it bugs (production build only since React dev won't throw it).
No worry just need time to investigate.

**Comment by MacKentoch** [comment]
This is weird... I don't reproduce this bug on my side.
I tried on Safari but this is not occurring.

Can you try on IE: [the demo link hosted on github](http://mackentoch.github.io/react-director-admin-template/)?
