### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by ksngits** [MacKentoch/react-director-admin-template#2]
Need to fix the following issues in the demo website
#1 
Mixed Content: The page at 'https://mackentoch.github.io/react-director-admin-template/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Lato'. This request has been blocked; the content must be served over HTTPS.

#2  When i click the simpletables in the 'https://mackentoch.github.io/react-director-admin-template/'
Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (app.vendor.bundle.js:6)
    at f.getHostNode (app.vendor.bundle.js:67)
    at Object.getHostNode (app.vendor.bundle.js:6)
    at Object.updateChildren (app.vendor.bundle.js:67)
    at d._reconcilerUpdateChildren (app.vendor.bundle.js:68)
    at d._updateChildren (app.vendor.bundle.js:68)
    at d.updateChildren (app.vendor.bundle.js:68)
    at d._updateDOMChildren (app.vendor.bundle.js:68)
    at d.updateComponent (app.vendor.bundle.js:68)
    at d.receiveComponent (app.vendor.bundle.js:68)
    at Object.receiveComponent (app.vendor.bundle.js:6)

**Comment by MacKentoch** [comment]
Hi @ksngits,

Thank you contribution.

Despite these are errors, this is normal since this react-director-admin-template is not finished at this time.

I'm currently focusing on another repository (fixing) so I don't have time to finish it.

I keep this issue open as a reminder.

**Comment by ksngits** [comment]
Also lacks responsiveness.

**Comment by MacKentoch** [comment]
#1 fixed

#2 work in progress. I plan to use [react-bootstrap-table](https://github.com/AllenFang/react-bootstrap-table) since a complete table I already used in production application.

**Comment by nadesan** [comment]
How i can include login page and authentication for admin template. Please guide me

**Comment by MacKentoch** [comment]
@nadesan With react-router 4 it is even easier than before.

Just add a route in your Root component:

```javascript
class Root extends Component {
  render() {
    return (
      <Provider store={store}>
        <div>
          <Router history={syncedHistory}>
            <ScrollTop>
              <Switch>
                <Route exact path="/login" component={Login} />
                <App />
                <Route component={PageNotFound} />
              </Switch>
            </ScrollTop>
          </Router>
        </div>
      </Provider>
    );
  }
}
```

I will soon (very soon) push this example (working example) in this template.

**Comment by MacKentoch** [comment]
@nadesan see it in action:
- go [preview](https://mackentoch.github.io/react-director-admin-template/#/)
- click on top navbar user menu (John Doe) 
- then click logout 

Then login in is a fake login so just enter anything to login.

**Comment by nadesan** [comment]
Please send me the code


*Thanks,*
*Nadesan G*
*Mobile:* +919944818535
Email: nadesan@ceino.com
skype id: nadesan1605

**Comment by nadesan** [comment]
Am running for a prod build (PORT 30) and in server. My dev build working fine but when i run with production its not working.Anyone please let me know how to solve this.

**Comment by nadesan** [comment]
Am trying to upload the code in node server. but its showing error in operating system. Please check the attached image.

![image](https://user-images.githubusercontent.com/17059675/33011269-72b1af8a-ce03-11e7-9b28-0229729c11d3.png)

**Comment by MacKentoch** [comment]
Hi @nadesan 

Please use at least NodeJS **6.x** since dependencies are often no more the same from **4.x**.
*There are less issues when dealing with 6.x and 8.x.*

- upgrade NodeJS to 6.x (*NOTE: better use nvm to deal with multiple NodeJS version if you still need 4.x*)
- then delete and reinstall node modules:

  ```bash
  rm -rf node_modules
  ```

  ```bash
  npm install
  ```

**Comment by nadesan** [comment]
![image](https://user-images.githubusercontent.com/17059675/33147576-4cd329aa-cfee-11e7-8e55-9431bec5132a.png)
Issue still not fixed in my ubuntu server. Please let me know the whats the issue. 

Have installed latest version of Node and npm.

**Comment by MacKentoch** [comment]
@nadesan 

For theses errors I suspect there are file name related:
- `macOS` *is not case sensitive* (*so import are resolve even if you forgot an upper case for example*
- `linux/unix` *is case sensitive* so it won't work

I will fix it since it crashes CI too (running on a linux)

**Comment by tichuot** [comment]
@MacKentoch 
I just fix all typo errors in the image of @nadesan and re-run, it still contain errors that I can't understand in the image below. I'm running it in Ubuntu 16.04, Node.js v9.4.0.
Many thanks!
![screenshot from 2018-01-17 09-41-34](https://user-images.githubusercontent.com/13705708/35022972-24ecbba6-fb6b-11e7-9501-f832753d2dff.png)
