### ISSUE TITLE
Template is not being loaded in the browser

### ISSUE THREAD

**Issue by kamleshwebtech** [MacKentoch/react-director-admin-template#20]
Mac OS

not able to load this template in chrome browser

http://mackentoch.github.io/react-director-admin-template/

getting errors in console:
Failed to load resource: the server responded with a status of 404 (Not Found)
2app.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)

Kindly fix it. Thanks a lot :)

**Comment by MacKentoch** [comment]
Thank you @kamleshwebtech !

There is an issue with a Github hosted website.

Serving website with `http` will now fail just I forcing `https` and it is ok.
