### ISSUE TITLE
Launch preview is not working

### ISSUE THREAD

**Issue by pmirandaarias** [MacKentoch/react-director-admin-template#3]
Launch preview is not working:

Mixed Content: The page at 'https://mackentoch.github.io/react-director-admin-template/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Lato'. This request has been blocked; the content must be served over HTTPS.
/public/assets/app.styles.css Failed to load resource: the server responded with a status of 404 (Not Found)
app.vendor.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
app.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
(index):1 Mixed Content: The page at 'https://mackentoch.github.io/react-director-admin-template/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Lato'. This request has been blocked; the content must be served over HTTPS.
app.styles.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by MacKentoch** [comment]
Hi @pmirandaarias 

Thank you for this issues I did not pay attention to that.

**Comment by MacKentoch** [comment]
fixed now.
