### ISSUE TITLE
prod server not run in browser 

### ISSUE THREAD

**Issue by venkat27raman** [MacKentoch/react-director-admin-template#6]
Hi , am run command npm run prod-sever its run correct but in browser showing blank page

**Comment by MacKentoch** [comment]
Hi @venkat27raman ,

You should have an error in the browser console so that nothing renders.
Can you have a look?

**Comment by venkat27raman** [comment]
In console am not get anything

regards,
Venkat Raman.

**Comment by MacKentoch** [comment]
And in the server console?

Ensure you have NodeJS 6.x minimum (Node JS 8 is event better).

**Comment by venkat27raman** [comment]
am using version this one. v6.12.0
in local host am getting like this

[image: Inline image 1]



in ubuntu server am get like this one


[image: Inline image 2]

this also showing success but in browser showing
like this

[image: Inline image 3]

regards,
Venkat Raman.

**Comment by venkat27raman** [comment]
hai ,

Still that issues pending to me . am using port 80 . please give suggestion

regards,
Venkat Raman.

**Comment by MacKentoch** [comment]
Please provide images, I just can read text like`[image: Inline image 3]`.

And please don't create multiple issues for the same one.
It is nice you open an issue, it helps, but duplicates will be counter-productive.

**Comment by venkat27raman** [comment]
ok sure.. 
![image 1](https://user-images.githubusercontent.com/34024440/33309702-0336d480-d445-11e7-85de-f7201f318c7c.png)
![image](https://user-images.githubusercontent.com/34024440/33309705-038185d4-d445-11e7-9f35-bc5469a4f73d.png)
![image 2](https://user-images.githubusercontent.com/34024440/33309708-03df8fc6-d445-11e7-934c-b5e550aabd13.png)

These are that images that am mentioned in previous reply

**Comment by MacKentoch** [comment]
You have an `EACCESS error` on port 3000.
This is beyond the scope of this boilerplate.

This is linked to your own environment (maybe you need to run sudo?).
Check if no other process is running on port the same port in localhost.

**Comment by MacKentoch** [comment]
It is related to your environment. 
I close this issue.
